import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatInputModule,
  MatIconModule,
  MatCardModule,
  MatSelectModule,
  MatChipsModule,
  MatSidenavModule,
  MatMenuModule,
  MatSlideToggleModule,
  MatGridListModule,
  MatTabsModule,
  MatRadioModule,
  MatToolbarModule,
  MatSliderModule,
  MatTooltipModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatSnackBarModule,
  MatDialogModule,
  MatProgressSpinnerModule,
  MatListModule,
  MatProgressBarModule,
  MatDatepickerModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatBadgeModule
} from '@angular/material';
@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatChipsModule,
    MatSidenavModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatTabsModule,
    MatRadioModule,
    MatTableModule,
    MatToolbarModule,
    MatSliderModule,
    MatTooltipModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSnackBarModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatBadgeModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatChipsModule,
    MatSidenavModule,
    MatMenuModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatTabsModule,
    MatRadioModule,
    MatTableModule,
    MatToolbarModule,
    MatSliderModule,
    MatTooltipModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatSnackBarModule,
    MatDialogModule,
    MatDatepickerModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatBadgeModule
  ],
  declarations: []
})
export class AngularMaterialComponentsModule {}
